const CONTACT={phone:'0559 19 99 11',tel:'tel:0559199911',mail:'contact@nassah-dz.com',addr:'Zone d\'activités Kourifa Mohamed, Eucalyptus, Alger',addrAr:'منطقة النشاطات كوريفة محمد، الكاليتوس، الجزائر',map:'https://www.google.com/maps/search/?api=1&query=Zone+d%27activit%C3%A9s+Kourifa+Mohamed+Eucalyptus+Alger',fb:'https://www.facebook.com/search/top?q=Nassah'};
const CATS=[
 {k:'all',fr:'Toute la gamme',ar:'كل المنتجات',em:'✨'},
 {k:'cuisine',fr:'Cuisine',ar:'المطبخ',em:'🍽️'},
 {k:'sols',fr:'Sols & surfaces',ar:'الأرضيات والأسطح',em:'🧽'},
 {k:'desinf',fr:'Désinfection',ar:'التعقيم',em:'🛡️'},
 {k:'sdb',fr:'Salle de bain & WC',ar:'الحمّام والمرحاض',em:'🚿'},
 {k:'linge',fr:'Linge & armoire',ar:'الملابس والخزانة',em:'👕'},
 {k:'hyg',fr:'Hygiène des mains',ar:'نظافة اليدين',em:'🫧'}];
const STD=[['Tenir hors de portée des enfants.','يُحفظ بعيدا عن متناول الأطفال.'],['Éviter le contact avec les yeux ; en cas de projection, rincer abondamment à l\'eau.','تجنّبوا ملامسة العينين، وعند التعرّض اشطفوا بوفرة بالماء.'],['Ne pas ingérer. Conserver dans l\'emballage d\'origine.','لا يُبتلع. يُحفظ في عبوته الأصلية.']];
const NOMIX=['Ne jamais mélanger avec un autre produit (javel, acide, ammoniaque) : risque de gaz dangereux.','لا يُخلط أبدا مع منتج آخر (جافيل، حمض، أمونياك): خطر انبعاث غاز ضار.'];
const P={
vaisselle:{cat:['cuisine'],name:'Liquide Vaisselle Citron',ar:'سائل الأواني بالليمون',type:'Liquide vaisselle',typeAr:'سائل غسل الأواني',img:'img/vaisselle.webp',post:'img/post-vaisselle.jpg',c1:'#ffe04a',c2:'#f2a900',ink:'#0a1a5c',
 slogan:'أواني لماعة، البطل ناصح',sloganFr:'Vaisselle qui brille, le héros c\'est Nassah',
 short:'Super dégraissant, parfum citron, en bidon économique de 3 L.',shortAr:'مزيل قوي للدهون بعطر الليمون، في عبوة اقتصادية 3 لتر.',
 desc:'Le liquide vaisselle Nassah au citron est présenté sur son étiquette comme « super dégraissant » : il s\'attaque aux graisses tenaces et laisse la vaisselle brillante et parfumée. Une formule puissante et économique pour la vaisselle de tous les jours.',
 descAr:'سائل الأواني ناصح بالليمون، مزيل قوي للدهون حسب ملصقه: يقضي على الدهون العنيدة ويترك الأواني لامعة ومعطّرة. تركيبة قوية واقتصادية للاستعمال اليومي.',
 tags:[['Super dégraissant','مزيل قوي للدهون'],['Parfum citron','عطر الليمون'],['Économique','اقتصادي']],fmt:'3 L',
 uses:[['Verser une petite dose sur une éponge humide ou dans l\'eau de lavage.','صبّوا كمية صغيرة على إسفنجة مبلّلة أو في ماء الغسيل.'],['Frotter assiettes, verres, casseroles et couverts.','افركوا الصحون والكؤوس والقدور والملاعق.'],['Rincer à l\'eau claire.','اشطفوا بالماء النظيف.']],cautions:STD},
degraissant:{cat:['cuisine'],name:'Dégraissant Optimal Action',ar:'مزيل الدهون أوبتيمال أكشن',type:'Spray dégraissant',typeAr:'بخاخ مزيل الدهون',img:'img/degraissant.webp',post:'img/post-degraissant-javelmousse.jpg',c1:'#ff9a3c',c2:'#e2470c',ink:'#fff',
 slogan:'اللمعان والنقاء لي يبقى',sloganFr:'L\'éclat et la propreté qui durent',
 short:'Combat tous types de graisses : plaques, hottes, fours et plans de travail.',shortAr:'يقضي على كل أنواع الدهون: الطباخات، الشفاطات، الأفران وأسطح العمل.',
 desc:'Le spray Dégraissant Optimal Action de Nassah « combat tous types de graisses » selon son étiquette. Il cible la graisse cuite des plaques de cuisson, hottes, fours et plans de travail, avec un pulvérisateur pratique pour les zones difficiles.',
 descAr:'بخاخ مزيل الدهون أوبتيمال أكشن من ناصح يقضي على كل أنواع الدهون حسب ملصقه. يستهدف الدهون المحروقة على الطباخات والشفاطات والأفران وأسطح العمل، ببخاخ عملي للأماكن الصعبة.',
 tags:[['Toutes graisses','كل أنواع الدهون'],['Pulvérisateur','بخاخ'],['Cuisine','المطبخ']],fmt:'750 ml',
 uses:[['Pulvériser directement sur la surface grasse.','بخّوا مباشرة على السطح الدهني.'],['Laisser agir quelques instants.','اتركوه يعمل بضع لحظات.'],['Essuyer avec une éponge ou un chiffon humide, puis rincer.','امسحوا بإسفنجة أو قطعة قماش مبلّلة ثم اشطفوا.']],cautions:STD},
cristal:{cat:['sols','sdb'],name:'Cristal Multi-usages',ar:'كريستال متعدد الاستعمالات',type:'Spray multi-usages',typeAr:'بخاخ متعدد الاستعمالات',img:'img/cristal.webp',post:'img/post-cristal.jpg',c1:'#a9dcff',c2:'#2b6fe8',ink:'#fff',
 slogan:'مضاد للبكتيريا ومضاد للصدأ',sloganFr:'Antibactérien et antirouille',
 short:'Le spray antibactérien et antirouille pour vitres, inox, robinets et surfaces.',shortAr:'البخاخ المضاد للبكتيريا والصدأ للزجاج، الإينوكس، الحنفيات والأسطح.',
 desc:'Cristal est le spray multi-usages de Nassah, avec la mention « antibactérien et antirouille » sur l\'étiquette. Dans sa nouvelle présentation, il s\'utilise sur les vitres, les surfaces en inox, la robinetterie et les plans de travail.',
 descAr:'كريستال هو بخاخ ناصح متعدد الاستعمالات، مضاد للبكتيريا ومكافح للصدأ حسب ملصقه. بحلته الجديدة، يُستعمل على الزجاج، الإينوكس، الحنفيات وأسطح العمل.',
 tags:[['Antibactérien','مضاد للبكتيريا'],['Antirouille','مضاد للصدأ'],['Multi-surfaces','متعدد الأسطح']],fmt:'500 ml',
 uses:[['Pulvériser à 20 cm de la surface.','بخّوا على بعد 20 سم من السطح.'],['Essuyer avec un chiffon propre et sec.','امسحوا بقطعة قماش نظيفة وجافة.'],['Pour les surfaces alimentaires, rincer à l\'eau claire.','بالنسبة لأسطح الطعام، اشطفوا بالماء النظيف.']],cautions:STD},
javel:{cat:['desinf','sdb','linge'],name:'Eau de Javel 12°',ar:'ماء جافيل 12°',type:'Eau de Javel',typeAr:'ماء جافيل',img:'img/javel.webp',post:'img/post-javel.jpg',c1:'#ffb13b',c2:'#1b2f9e',ink:'#fff',
 slogan:'يطهر، ينظف، يبيض',sloganFr:'Désinfecte, nettoie, blanchit',
 short:'Javel 12° chlorométrique : désinfecte, nettoie et blanchit. Bidon de 3 L.',shortAr:'جافيل 12 درجة كلورومترية: يطهر، ينظف ويبيض. عبوة 3 لتر.',
 desc:'L\'Eau de Javel Nassah à 12° chlorométrique désinfecte, nettoie et blanchit. Pour les sols, carrelages, éviers et sanitaires, et pour blanchir le linge blanc, à diluer selon l\'usage.',
 descAr:'ماء جافيل ناصح بـ12 درجة كلورومترية يطهر، ينظف ويبيض. للأرضيات، البلاط، المغاسل والمراحيض، ولتبييض الملابس البيضاء، يُخفّف حسب الاستعمال.',
 tags:[['12° chlorométrique','12 درجة كلورومترية'],['Désinfecte','يطهر'],['Blanchit','يبيض']],fmt:'3 L',
 uses:[['Diluer dans l\'eau froide selon le mode d\'emploi de l\'étiquette.','خفّفوه في الماء البارد حسب إرشادات الملصق.'],['Appliquer sur la surface, laisser agir quelques minutes.','ضعوه على السطح واتركوه يعمل بضع دقائق.'],['Rincer à l\'eau claire et aérer la pièce.','اشطفوا بالماء النظيف وهوّوا الغرفة.']],cautions:[NOMIX,...STD]},
'javel-mousse':{cat:['desinf','sdb'],name:'Javel Moussante Parfumée',ar:'جافيل رغوي معطّر',type:'Javel moussante',typeAr:'جافيل رغوي',img:'img/javel-mousse.webp',post:'img/post-degraissant-javelmousse.jpg',c1:'#dbeeff',c2:'#2e5fe0',ink:'#0a1a5c',
 slogan:'جافيل رغوي يطهر ويعطر',sloganFr:'La javel qui mousse, désinfecte et parfume',
 short:'Désinfecte et parfume, au parfum eucalyptus. Bidon de 1,85 L.',shortAr:'يطهر ويعطّر، بعطر الكاليتوس. عبوة 1.85 لتر.',
 desc:'La Javel Moussante de Nassah associe la désinfection de la javel à une mousse qui adhère mieux aux surfaces, avec un parfum eucalyptus. Idéale pour les sanitaires, carrelages et sols.',
 descAr:'جافيل ناصح الرغوي يجمع بين تعقيم الجافيل ورغوة تلتصق بالأسطح، بعطر الكاليتوس. مثالي للمراحيض والبلاط والأرضيات.',
 tags:[['Moussante','رغوي'],['Parfum eucalyptus','عطر الكاليتوس'],['Désinfecte','يطهر']],fmt:'1,85 L',
 uses:[['Appliquer pur ou dilué sur la surface à traiter.','ضعوه صافيا أو مخففا على السطح.'],['Laisser agir la mousse quelques minutes.','اتركوا الرغوة تعمل بضع دقائق.'],['Rincer à l\'eau claire.','اشطفوا بالماء النظيف.']],cautions:[NOMIX,...STD]},
sani:{cat:['sols'],name:'Sani Lavande',ar:'صاني لافاند',type:'Nettoyant sols',typeAr:'منظف الأرضيات',img:'img/sani.webp',post:'img/post-sani.jpg',c1:'#b9c8ff',c2:'#3f49d8',ink:'#fff',
 slogan:'خفيف ظريف',sloganFr:'Léger, parfumé, efficace',
 short:'Le nettoyant sols au parfum lavande pour un intérieur frais.',shortAr:'منظف الأرضيات بعطر اللافاند لبيت منعش.',
 desc:'Sani Lavande est le nettoyant sols de Nassah. Il nettoie carrelages et sols lavables et laisse un parfum de lavande frais dans toute la maison.',
 descAr:'صاني لافاند هو منظف الأرضيات من ناصح. ينظف البلاط والأرضيات القابلة للغسل ويترك عطر لافاند منعشا في كل البيت.',
 tags:[['Sols & carrelages','الأرضيات والبلاط'],['Parfum lavande','عطر اللافاند'],['Au quotidien','للاستعمال اليومي']],fmt:'Flacon',
 uses:[['Verser un bouchon dans un seau d\'eau.','صبّوا غطاء في دلو ماء.'],['Laver le sol à la serpillière.','امسحوا الأرضية بالممسحة.'],['Pas besoin de rincer.','لا حاجة للشطف.']],cautions:STD},
'esprit-sel':{cat:['sdb'],name:'Esprit de Sel',ar:'روح الملح',type:'Détartrant',typeAr:'مزيل الترسبات',img:'img/esprit-sel.webp',post:'img/post-esprit-sel.jpg',c1:'#ff6a5c',c2:'#b3121a',ink:'#fff',
 slogan:'60 سنة من الوجود على مد أجيال',sloganFr:'60 ans de présence, de génération en génération',
 short:'Le détartrant des sanitaires : WC, lavabos, tartre et dépôts calcaires.',shortAr:'مزيل الترسبات للمراحيض والمغاسل والكلس.',
 desc:'L\'Esprit de Sel Nassah, dans sa bouteille rouge reconnaissable, élimine le tartre et les dépôts calcaires des WC, lavabos et sanitaires. Un produit acide à manipuler avec précaution.',
 descAr:'روح الملح ناصح، بقارورته الحمراء المعروفة، يزيل الكلس والترسبات من المراحيض والمغاسل. منتج حمضي يُستعمل بحذر.',
 tags:[['Anti-tartre','مزيل الكلس'],['WC & sanitaires','المراحيض'],['720 ml','720 مل']],fmt:'720 ml',
 uses:[['Porter des gants et aérer la pièce.','البسوا قفازات وهوّوا الغرفة.'],['Verser une petite quantité sur la zone entartrée, laisser agir.','صبّوا كمية صغيرة على مكان الكلس واتركوه يعمل.'],['Brosser puis rincer abondamment.','افركوا بالفرشاة ثم اشطفوا بوفرة.']],cautions:[NOMIX,['Produit acide et corrosif : protéger les yeux, la peau et les surfaces fragiles (marbre, émail abîmé).','منتج حمضي أكّال: احموا العينين والجلد والأسطح الهشة (الرخام).'],...STD]},
cresyl:{cat:['desinf'],name:'Crésyl',ar:'كريزيل',type:'Désinfectant',typeAr:'مطهّر',img:'img/cresyl.webp',post:'img/post-cresyl.jpg',c1:'#8fd26b',c2:'#3b2a12',ink:'#fff',
 slogan:'ينظف ويطهر',sloganFr:'Nettoie et désinfecte',
 short:'Nettoie et désinfecte : caniveaux, sols, et bâtiments d\'élevage avicole.',shortAr:'ينظف ويطهر: المجاري، الأرضيات ومباني تربية الدواجن.',
 desc:'Le Crésyl Nassah nettoie et désinfecte. Il s\'adresse aussi bien à l\'entretien des caniveaux et sols qu\'aux éleveurs, notamment pour l\'hygiène des bâtiments d\'élevage de volailles.',
 descAr:'كريزيل ناصح ينظف ويطهر. يناسب تنظيف المجاري والأرضيات، وكذلك المربّين خاصة لنظافة مباني تربية الدواجن.',
 tags:[['Désinfectant','مطهّر'],['Élevages','المزارع'],['720 ml','720 مل']],fmt:'720 ml',
 uses:[['Diluer dans l\'eau selon le dosage indiqué sur l\'étiquette.','خفّفوه في الماء حسب الجرعة المذكورة على الملصق.'],['Appliquer sur les sols et surfaces à désinfecter.','ضعوه على الأرضيات والأسطح المراد تطهيرها.'],['Aérer les locaux après application.','هوّوا المكان بعد الاستعمال.']],cautions:[NOMIX,...STD]},
lessive:{cat:['linge'],name:'Lessive Linge Machine',ar:'سائل غسيل الملابس',type:'Lessive liquide',typeAr:'سائل الغسيل',img:null,post:'img/post-lessive.jpg',c1:'#fff1c2',c2:'#e3a21a',ink:'#0a1a5c',
 slogan:'يقضي على كل أنواع البقع',sloganFr:'Vient à bout de toutes les taches',
 short:'Au savon de Marseille, 2 en 1, 28 lavages, toutes machines.',shortAr:'بصابون مرسيليا، 2 في 1، 28 غسلة، لكل أنواع الآلات.',
 desc:'La Lessive Linge Machine Nassah au savon de Marseille est une formule 2 en 1 « efficace & économique ». Son bidon de 3 L assure 28 lavages et convient à tous types de machines.',
 descAr:'سائل غسيل الملابس ناصح بصابون مرسيليا، تركيبة 2 في 1 فعالة واقتصادية. عبوة 3 لتر تكفي 28 غسلة وتناسب كل أنواع الآلات.',
 tags:[['Savon de Marseille','صابون مرسيليا'],['28 lavages','28 غسلة'],['2 en 1','2 في 1']],fmt:'3 L',
 uses:[['Doser selon le degré de salissure et la taille de la charge.','قيسوا الكمية حسب درجة الأوساخ وحجم الحمولة.'],['Verser dans le bac à lessive ou directement dans le tambour.','صبّوه في درج الغسيل أو مباشرة في الأسطوانة.'],['Lancer le programme adapté au textile.','شغّلوا البرنامج المناسب للقماش.']],cautions:STD},
'savon-mains':{cat:['hyg'],name:'Savon Liquide Mains',ar:'صابون سائل لليدين',type:'Savon liquide',typeAr:'صابون سائل',img:'img/savon-mains.webp',post:'img/post-savon-mains.jpg',c1:'#e7f1ff',c2:'#5b8ff0',ink:'#0a1a5c',
 slogan:'يترغون ويخلي النقاء',sloganFr:'Il mousse et laisse la pureté',
 short:'Antibactérien, parfum Dover douce, flacon pompe 500 ml.',shortAr:'مضاد للبكتيريا، بعطر دوفر دوس، قارورة بمضخة 500 مل.',
 desc:'Le savon liquide pour les mains Nassah, porteur de la mention « antibactérien », allie propreté et douceur. Parfum Dover douce, en flacon pompe de 500 ml.',
 descAr:'صابون ناصح السائل لليدين، مضاد للبكتيريا، يجمع بين النظافة والنعومة. بعطر دوفر دوس، في قارورة بمضخة 500 مل.',
 tags:[['Antibactérien','مضاد للبكتيريا'],['Propreté & douceur','نظافة ونعومة'],['Flacon pompe','قارورة بمضخة']],fmt:'500 ml',
 uses:[['Appliquer une noisette sur les mains mouillées.','ضعوا قليلا على اليدين المبلّلتين.'],['Frotter pendant 20 secondes.','افركوا لمدة 20 ثانية.'],['Rincer et sécher.','اشطفوا وجفّفوا.']],cautions:[['Usage externe uniquement.','للاستعمال الخارجي فقط.'],['Éviter le contact avec les yeux.','تجنّبوا ملامسة العينين.'],['Tenir hors de portée des jeunes enfants.','يُحفظ بعيدا عن الأطفال الصغار.']]},
antimites:{cat:['linge'],name:'Anti-Mites en Billes',ar:'ضد العث — كويرات',type:'Anti-mites',typeAr:'ضد العث',img:'img/antimites.webp',post:'img/post-antimites.jpg',c1:'#fff17a',c2:'#d8a800',ink:'#0a1a5c',
 slogan:'يقضي على العث ويمنعو يدور بقشك',sloganFr:'Stoppe les mites, protège vos vêtements',
 short:'Billes à base de naphtaline pour armoires, penderies et valises. 115 g.',shortAr:'كويرات بالنفطالين للخزائن والحقائب. 115 غ.',
 desc:'Les billes anti-mites Nassah à base de naphtaline protègent la laine et les textiles dans les armoires, penderies et valises. Faciles à utiliser, elles gardent vos affaires d\'hiver à l\'abri des mites.',
 descAr:'كويرات ناصح ضد العث بالنفطالين تحافظ على الصوف والمنسوجات في الخزائن والحقائب. سهلة الاستعمال وتحمي ملابس الشتاء من العث.',
 tags:[['Armoires & valises','الخزائن والحقائب'],['Protège la laine','يحمي الصوف'],['115 g','115 غ']],fmt:'115 g',
 uses:[['Placer quelques billes dans un sachet ou un coin de l\'armoire.','ضعوا بعض الكويرات في كيس أو زاوية الخزانة.'],['Éviter le contact direct avec les vêtements.','تجنّبوا الملامسة المباشرة مع الملابس.'],['Renouveler lorsque les billes ont disparu.','جدّدوها عند اختفائها.']],cautions:[['Produit dangereux : ne jamais laisser à la portée des enfants.','منتج خطير: لا يُترك أبدا في متناول الأطفال.'],['Ne pas ingérer, se laver les mains après manipulation.','لا يُبتلع، اغسلوا اليدين بعد الاستعمال.'],['Aérer les vêtements avant de les porter.','هوّوا الملابس قبل لبسها.']]}
};
const ORDER=['vaisselle','javel','sani','cristal','savon-mains','lessive','degraissant','javel-mousse','esprit-sel','cresyl','antimites'];
const NEEDS=[
 {id:'gras',em:'🍳',t:['Dégraisser la cuisine','إزالة دهون المطبخ'],p:['degraissant','vaisselle']},
 {id:'vais',em:'🍽️',t:['Faire briller la vaisselle','أواني لامعة'],p:['vaisselle']},
 {id:'sol',em:'🧹',t:['Laver et parfumer les sols','تنظيف وتعطير الأرضيات'],p:['sani','javel-mousse']},
 {id:'wc',em:'🚽',t:['Détartrer les WC','إزالة كلس المرحاض'],p:['esprit-sel']},
 {id:'desinf',em:'🦠',t:['Désinfecter les surfaces','تطهير الأسطح'],p:['javel','cristal']},
 {id:'vitre',em:'🪟',t:['Vitres, inox et robinets','الزجاج والإينوكس والحنفيات'],p:['cristal']},
 {id:'linge',em:'👕',t:['Laver le linge','غسل الملابس'],p:['lessive','javel']},
 {id:'mite',em:'🧥',t:['Protéger la laine des mites','حماية الصوف من العث'],p:['antimites']},
 {id:'ferme',em:'🐔',t:['Hygiène d\'un élevage','نظافة المزرعة'],p:['cresyl']},
 {id:'main',em:'🫧',t:['Se laver les mains','غسل اليدين'],p:['savon-mains']}];
